# Generated by Django 4.1.7 on 2024-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_codes_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='datatime',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='issubscibed',
            field=models.BooleanField(default=False),
        ),
    ]
